<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '254197291a7f36cdf876d8c2d43ea313' => $baseDir . '/includes/media-credit-template.php',
);
