<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Media_Credit\\Vendor\\Dice\\' => array($vendorDir . '/level-2/dice'),
);
